name: tencent_cloud_chat_message
description: A component for displaying a list of messages and dealing with everything related to sending and receiving messages for Tencent Cloud Chat.
version: 1.2.0
repository: https://github.com/TencentCloud/chat-uikit-flutter/tree/v2/tencent_cloud_chat_message
homepage: https://trtc.io/products/chat?utm_source=gfs&utm_medium=link&utm_campaign=%E6%B8%A0%E9%81%93&_channel_track_key=k6WgfCKn

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  record: ^5.0.1
  fc_native_video_thumbnail: ^0.7.0
  file_picker: ^6.1.1
  pull_to_refresh: ^2.0.0
  flutter_list_view: ^1.1.18
  tencent_cloud_chat: ^1.2.0
  tencent_cloud_chat_common: ^1.2.0
  http: ^1.1.0
  card_swiper: ^3.0.1
  photo_view: ^0.14.0
  better_player_plus: ^1.0.5
  open_file: ^3.3.2
  haptic_feedback: ^0.4.2
  vibration: ^1.8.4
  scroll_to_index: ^3.0.1
  pasteboard: ^0.2.0
  url_launcher: ^6.2.2
  desktop_drop: ^0.4.4
  dotted_border: ^2.1.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - images/
    - images/stickers/qq/
# To add assets to your package, add an assets section, like this:

#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
